### ISSUE TITLE
Pushgateway with basic auth

### ISSUE THREAD

**Issue by twiden** [aerogear/keycloak-metrics-spi#145]
Is there a way to push metrics to a Prometheus Pushgateway that has basic auth enabled? 

(Enabling basic auth in Pushgateway protects all HTTP endpoints including POST metrics)

**Comment by hashworks** [comment]
Example: https://github.com/prometheus/client_java/blob/main/integration_tests/it_pushgateway/src/main/java/io/prometheus/client/it/pushgateway/ExampleBatchJob.java#L32C13-L32C91
