### ISSUE TITLE
No license declared

### ISSUE THREAD

**Issue by croeck** [aerogear/keycloak-metrics-spi#15]
Hi guys,

I was stumbling upon your project while looking for a Keycloak / Prometheus integration. Your SPI looks very promising! However, I wonder in which way I could use it.

Would you mind applying a license to the repo?

Thanks 
Cedric

**Comment by oliver-steinbrecher** [comment]
That would be great!

**Comment by Badmiaoo** [comment]
Please, add a licence :smile:

**Comment by aliok** [comment]
hi @croeck we always use Apache License 2.0 but forgot to add the license file. I will do that

**Comment by Badmiaoo** [comment]
Thank you very much !!!
