### ISSUE TITLE
Broken Grafana Dashboard link

### ISSUE THREAD

**Issue by jesuino** [aerogear/keycloak-metrics-spi#152]
## Description
In README that's a reference to a Grafana dashboard, but the link is broken (https://grafana.com/dashboards/10441)

## Expected Behavior
Link should not be broken

## Actual Behavior
404 result when clicking on the link

## Environment

N/A

## Steps to reproduce

Click on the link from the README

**Comment by pb82** [comment]
thanks, this should be fixed now
