### ISSUE TITLE
Metrics not available after upgrading to KC 21 and SPI 3.0.0

### ISSUE THREAD

**Issue by Jojoooo1** [aerogear/keycloak-metrics-spi#163]
## Description
Metrics are not being shown anymore

![Screenshot from 2023-04-01 11-24-34](https://user-images.githubusercontent.com/17641873/229295077-e5a358ad-172f-44bf-a4c9-d0c2a6d058d0.png)

## Expected Behavior
Metrics should still be available after upgrading.

## Actual Behavior
Metrics seem to not work anymore after upgrading.

## Environment

* Spi version: keycloak-metrics-spi-3.0.0
* Project Versions: Keycloak 21.0.2
* Helm Version: bitnami 14.0.0

## Cause
Seems that keycloak_logins is not available anymore in the metrics list.

**Comment by Jojoooo1** [comment]
fixed by moving to keycloak_logins_total

**Comment by ampc** [comment]
I'm having the same issue after udpating to KC 21 (also using the bitnami chart).

**Comment by ThoreKr** [comment]
i just see a lot of metrics are no longer populated, mostly related to `keycloak_user_...` when checking the metrics endpoint there is only the descriptive comment, but no more metric.
