### ISSUE TITLE
Keycloak 25.0.6 not showing all featured events

### ISSUE THREAD

**Issue by YoudhveerPanwar** [aerogear/keycloak-metrics-spi#216]
## Description
Keycloak 25.0.6 not showing all featured events

## Expected Behavior
Expecting all metrics mentioned under feature events - https://github.com/aerogear/keycloak-metrics-spi like keycloak_login_attempts:
`# HELP keycloak_login_attempts Total number of login attempts`
`# TYPE keycloak_login_attempts counter`
`keycloak_login_attempts{realm="test",provider="keycloak",client_id="account"} 3.0`
`keycloak_login_attempts{realm="test",provider="github",client_id="application1"} 2.0`

keycloak_login_total :
`# HELP keycloak_logins_total Total successful logins`
`# TYPE keycloak_logins_total counter`
`keycloak_logins_total{realm="test",provider="keycloak",client_id="account"} 3.0`
`keycloak_logins_total{realm="test",provider="github",client_id="application1"} 2.0`

## Actual Behavior
keycloak_login_total :
`# HELP keycloak_logins_total Total successful logins`
`# TYPE keycloak_logins_total counter`

keycloak_login_attempts:
`# HELP keycloak_login_attempts Total number of login attempts`
`# TYPE keycloak_login_attempts counter`

## Environment

* Keycloak version : 25.0.6
* Bitnami helmchart: https://artifacthub.io/packages/helm/bitnami/keycloak/22.2.6
* Promteheous kube operator Versions: bitnami version -- kube-prometheus-stack-62.7.0.tgz

## Steps to reproduce
Installed both charts  (Keycloak and kube-prometheus-stack) from bitnami and test by exposing ports

Getting following metrics

[keycloak-metrics.txt](https://github.com/user-attachments/files/17148726/keycloak-metrics.txt)

**Comment by yaacine** [comment]
I'm having the same issue, with the exact same configuration

**Comment by YoudhveerPanwar** [comment]
Closing this issue as we have find the fix,
we enabled  Events -> Config. The Event Listeners configuration should have an entry named metrics-listener.
<img width="1766" alt="Screenshot 2024-10-08 at 22 11 00" src="https://github.com/user-attachments/assets/fd11e4f3-c12a-4057-a79a-0048c60977c8">
