### ISSUE TITLE
Support Question: Unsure if I'm setting up the SPI correctly

### ISSUE THREAD

**Issue by johnmeehan123** [aerogear/keycloak-metrics-spi#27]
## Description
Unsure if I'm setting this up correctly, no indication that I am

## Expected Behavior
Data to be displayed under localhost/auth/realms/master/metrics

## Actual Behavior
Nothing being displayed

## Steps to reproduce
Firstly unsure if this is off topic so apologies if it is. I've been trying to setup this project today but due to a lack of understanding around jar files etc, unsure if i'm doing it correctly

Steps I took:
1) Downloaded and unzipped github repo to host machine
2) Ran the command stated "./gradlew jar"
3) Created a new directory inside the keycloak container called providers (/opt/jboss/keycloak/providers)
Copied the jar file from /build/libs to the providers folder inside a Keycloak Docker container
Went to Keycloak GUI and went to mange -> events -> config and added "metrics-listener" as a named entry 

What's the best way to find out if my configurations worked correctly?  I assume some file(s) are written to on login/logout requests however I can't find any at the moment.

**Comment by pb82** [comment]
@johnmeehan123 If you were able to add the `metrics-listener` then it looks like the SPI has been loaded successfully. Does Keycloak otherwise work find, can you access it's UI? If you're running it locally then the URL should include a port (like localhost:8080/auth/realms/master/metrics).

You can also grep the logs for `metrics`. If the SPI is loaded correctly you shoud see a few log entries mentioning it.

**Comment by johnmeehan123** [comment]
@pb82 Sorry I should have specified. I added metrics-listener manually. It didn't autocomplete. Yes I can access the UI. It gives the error that it couldn't find this provider when I look at the docker logs.

I literally just dropped the jar file into the providers subdirectory. Should I have done anything with it once there (run it etc)?

**Comment by johnmeehan123** [comment]
@pb82 After some more playing with it I've actually figured it out. I ran ./gradlew jar and copied the resulting file into /opt/jboss/keycloak/standalone/deployments.
It worked fine after that. Thanks for the help and sorry for wasting your time
