### ISSUE TITLE
Keycloak and Prometheus versions shouldbe configurable from the command line

### ISSUE THREAD

**Issue by saibot94** [aerogear/keycloak-metrics-spi#28]
## Description
The Keycloak and Prometheus versions should be configurable for people that use different versions of Keycloak.

## Expected Behavior
Configs can be configured via the properties file and via the command line.

## Actual Behavior
Configs are hardcoded.

**Comment by pb82** [comment]
Closing since https://github.com/aerogear/keycloak-metrics-spi/pull/29 is merged.
