### ISSUE TITLE
Release with Metrics filter

### ISSUE THREAD

**Issue by dchrzascik** [aerogear/keycloak-metrics-spi#31]
I find your library really useful, especially the recent addition - metrics filter. I have following questions:

- do you plan to release it in nearby future? I would like to use new filter and I don't want to have a dependency to a SNAPSHOT
- do you plan to publish artifacts on some public repository? I think that would be great and ease using your spi

**Comment by wei-lee** [comment]
@dchrzascik Yes, I think these are good ideas and we will try to release to a public repo ASAP.

**Comment by pb82** [comment]
@dchrzascik There is a new release containing the response time filter now: https://github.com/aerogear/keycloak-metrics-spi/releases/tag/1.0.1

Currently we only have the artifact hosted on Github, we might release it to Maven Central in the future.

**Comment by dchrzascik** [comment]
Great, thanks.
