### ISSUE TITLE
Jar file not available for release 1.0.2

### ISSUE THREAD

**Issue by pamiel** [aerogear/keycloak-metrics-spi#41]
## Description
Jar file is not available for release 1.0.2.

## Expected Behavior
Jar file be available as asset of release 1.0.2 https://github.com/aerogear/keycloak-metrics-spi/releases/tag/1.0.2

And thanks for the great job!

**Comment by grdryn** [comment]
@pb82 do we expect people to build their own jar files, or should we build one and have it as a release artifact here on GitHub?

**Comment by pb82** [comment]
@pamiel @grdryn My fault, i didn't upload the jar file when creating the 1.0.2 release. Doing that now.

**Comment by pb82** [comment]
The jar file is now available under the release: https://github.com/aerogear/keycloak-metrics-spi/releases/tag/1.0.2
