### ISSUE TITLE
newer prometheus and keycloak version

### ISSUE THREAD

**Issue by Ferdinanddb** [aerogear/keycloak-metrics-spi#48]
Hey! This is more a question than an issue :-) 

it is a cool project but I wanted to know if I could use it with newer versions of Prometheus (v2.9.2) and Keycloak (v6.0.1) ?

I've tried just by running the default `./gradlew jar` and it seems to work with my keycloak and prometheus versions mentionned earlier.

**Comment by pb82** [comment]
Hi @Ferdinanddb. You can specify the version of the Keycloak and Prometheus artifacts as gradle properties. See https://github.com/aerogear/keycloak-metrics-spi#configurable-versions-for-some-packages

Is that what you were looking for?

**Comment by Ferdinanddb** [comment]
I saw it by reading the readme but i've looked at where you are the image is pulled adding  and I haven't seen choices for recent Prometheus version, I was wondering if it is because of compatibility issue or else..

**Comment by pb82** [comment]
Are you referring to the jar files in the Github releases? Or to a docker image? The released jar files are compiled using the default versions of Keycloak and Prometheus. I'm not aware of any compatibility issues, so if you want you can always build your own jar passing the versions you need as parameters.

**Comment by Ferdinanddb** [comment]
What I've checked is this URL: https://repo.jfrog.org/artifactory/libs-release-bintray/io/prometheus/simpleclient/ . This URL is used when running the command to create the JAR file. And the last version available for Prometheus is 0.6.0. WHat I wanted to know is if there is a way to specify the version 2.9.2 instead of the version 0.6.0?

**Comment by pb82** [comment]
Ah sorry i thought you wanted to override the version of the keycloak and prometheus libraries used to compile the jar. I would say as long as it works for you, there is no need to change it. 

`0.3.0` does not refer to a Prometheus version here, but to the version of the Prometheus client libraries(simple_client). I don't think you need to override it unless there is something in newer releases that you want: https://github.com/prometheus/client_java/releases

**Comment by Ferdinanddb** [comment]
Thank you for your answer, I didn't know about the Prometheus client libraries.. I'm closing the issue :-)
