### ISSUE TITLE
Metrics doesn't work in a keycloak cluster

### ISSUE THREAD

**Issue by sxd** [aerogear/keycloak-metrics-spi#50]
If you setup a keycloak cluster with two or more nodes, when you ask to node1 you get X number of logins and when you ask to node2 you can get X-2 number of logins.

This it's because you put a loadbalancer in front with a round-robin  balance and you ask to each node independently. 

There's any plan to store and read this data from the database or at least share the data between nodes?

**Comment by sorenvalentinjp** [comment]
We have the same problem. A solution to this would be to add support for pushing to a prometheus pushgateway. Then there wont be an issue with the loadbalancer in front of the keycloak instances.
