### ISSUE TITLE
keycloak_logins is not exported

### ISSUE THREAD

**Issue by langemar** [aerogear/keycloak-metrics-spi#57]
## Description
The keycloak_logins counter is described but not exported while scraping metrics endpoint

## Expected Behavior
keycloak_login should be exported with a value

## Actual Behavior
No value is exported. The Only keycloak related values exported are:

- keycloak_response_errors
- keycloak_request_duration (containing reasonable realm values)

All other metrics are described but without any value

## Environment

* Operating system: CentOS Linux 7.1906 Atomic Host
* OpenShift versions: OKD 3.11.0+739ab57-285
* k8s version: 1.11.0+d4cacc0
* Project Versions: 1.0.3 u. 1.0.4 / Keycloak 7.0.0 (jboss/keycloak:7.0.0)

## Steps to reproduce
Keycloak runs as an single instance statefulset with one realm created. This realm contains an user. The user login is visible in the kc logs but scraping the metrics endpoint does not provide a keycloak_logins counter

**Comment by pb82** [comment]
@langemar did you enable the metrics listener for the realm? Even if the extension is loaded, you still need to add the listener under Admin -> Events in the Keycloak admin console.

**Comment by langemar** [comment]
@pb82 thank you very much, this was the problem :) Please excuse my noobish question.

I leave this ticket open as it might still be nice to have this information in an quick start guide.
