### ISSUE TITLE
Endpoint metrics URL not found

### ISSUE THREAD

**Issue by ralbon** [aerogear/keycloak-metrics-spi#58]
## Description
We use Keycloak docker image jboss/keycloak:7.0.0 configured in a standalone-ha mode with 2 instances. It's working well.
We followed instructions to use SPI (download it, place it under xxx/providers, and add it through UI).
Logs seem to confirmed it is configured : 
`12:59:29,851 INFO  [org.jboss.aerogear.keycloak.metrics.MetricsEventListener] (default task-3) Received admin event of type UPDATE (REALM) in realm master
13:00:07,319 INFO  [org.jboss.aerogear.keycloak.metrics.MetricsEventListener] (default task-3) Received admin event of type UPDATE (REALM) in realm master` 

## Expected Behavior
Metrics should be exposed in <URL>/auth/realms/master/metrics

## Actual Behavior
I got a 404 when I tried to access to <URL>/auth/realms/master/metrics

I found some warning at initialisation related to metrics-listener
`12:49:50,140 WARN  [org.keycloak.services] (ServerService Thread Pool -- 72) KC-SERVICES0047: metrics-listener (org.jboss.aerogear.keycloak.metrics.MetricsEventListenerFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice`

Any Idea ? 

Thank you for your help

**Comment by pb82** [comment]
Since you have two instances, is it possible that the SPI is only installed in one of them? Not quite sure what else could be the problem here.

**Comment by ralbon** [comment]
We found the issue, it was on our side.

We installed it in both of them but due to our configuration (keycloak not bind to all interfaces) our tests didn't work.

Thank for your answer.

**Comment by stiaga** [comment]
Hi,
I'm in the same situation.
My keycloak installation binds to all interfaces.

Please help me.
