### ISSUE TITLE
Route tag causing huge cardinality

### ISSUE THREAD

**Issue by cablespaghetti** [aerogear/keycloak-metrics-spi#63]
## Description
We found our Prometheus server was using a lot of memory and traced it to the face one of the tags used is "route" which includes the ID for each user, which is our case is in the tens of thousands.

keycloak_request_duration_count{method="GET",route="/admin/realms/<myrealm>/users/<id>",} 13.0

It would be good if this tag could be disabled as an option.

Currently on version 1.0.1 but I think this is the case in the latest version as well.

**Comment by pb82** [comment]
fixed in #65 (release 2.0.0)
