### ISSUE TITLE
Huge number of keycloak_request_duration_bucket entries

### ISSUE THREAD

**Issue by michaelknurr** [aerogear/keycloak-metrics-spi#64]
## Description
After installing the metrics-spi, we saw a huge number of keycloak_request_duration_bucket entries in blocks of 11 entries fro every single user. Since we have a high number of users, the metrics page takes forever to load. 

## Expected Behavior
Reduce size and load time of the metrics page to a reasonable value.

## Actual Behavior
The total size of the metrics page is more than 300 MB (!!!)

## Environment
Standalone Keycloak v3.4.2

* Operating system:
Ubuntu 18.04.4 LTS

* Project Versions: 

## Steps to reproduce
Open metrics page.

**Comment by pb82** [comment]
@michaelknurr Ok, that's definitely excessive. We should probably exclude some endpoints from recording (e.g. the user endpoints).
