### ISSUE TITLE
is there away to get instance hostname in the labels for keycloak metrics

### ISSUE THREAD

**Issue by AmjadHussainSyed** [aerogear/keycloak-metrics-spi#77]
## Description
Add a brief and meaningful description.
i'm not able to find a way to get instance hostname in labels for the keycloak metrics instead of ip address. is it supported?
## Expected Behavior
Describe the expected behaviour. 
i need to see the hostname.
## Actual Behavior
Describe the current/actual behaviour.
instance=ip-address
## Environment
prod
* Operating system:  Red Hat Enterprise Linux - 8.2 (Ootpa)
* OpenShift versions: kubernetes(eks - 1.16)
* Project Versions:  10.0.1 keycloak version
## Steps to reproduce
Describe all steps and pre-requirements which are required to be performed in order to reproduce this scenario. ( E.g 1. Action, 2. Action ... )

**Comment by pb82** [comment]
But I think the proper way to do this would be to join the metric with another one in Prometheus that contains the service / host or node name. For example: https://stackoverflow.com/a/51023463
